<?php

namespace ContainerXvLjpJL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IhCOLLoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IhCOLLo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IhCOLLo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\VoyageController::delete' => ['privates', '.service_locator.0aFFzDT', 'get_ServiceLocator_0aFFzDTService', true],
            'App\\Controller\\VoyageController::edit' => ['privates', '.service_locator.0aFFzDT', 'get_ServiceLocator_0aFFzDTService', true],
            'App\\Controller\\VoyageController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\VoyageController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\VoyageController::show' => ['privates', '.service_locator.cRw86ao', 'get_ServiceLocator_CRw86aoService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\VoyageController:delete' => ['privates', '.service_locator.0aFFzDT', 'get_ServiceLocator_0aFFzDTService', true],
            'App\\Controller\\VoyageController:edit' => ['privates', '.service_locator.0aFFzDT', 'get_ServiceLocator_0aFFzDTService', true],
            'App\\Controller\\VoyageController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\VoyageController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\VoyageController:show' => ['privates', '.service_locator.cRw86ao', 'get_ServiceLocator_CRw86aoService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\VoyageController::delete' => '?',
            'App\\Controller\\VoyageController::edit' => '?',
            'App\\Controller\\VoyageController::index' => '?',
            'App\\Controller\\VoyageController::new' => '?',
            'App\\Controller\\VoyageController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\VoyageController:delete' => '?',
            'App\\Controller\\VoyageController:edit' => '?',
            'App\\Controller\\VoyageController:index' => '?',
            'App\\Controller\\VoyageController:new' => '?',
            'App\\Controller\\VoyageController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
