<?php

<<<<<<<< HEAD:var/cache/dev/ContainerSBytbox/getValidator_ExpressionLanguageService.php
namespace ContainerSBytbox;

========
namespace ContainerLVMUex8;
>>>>>>>> fd6f3db (PDO INCLUDE MYSQL):var/cache/dev/ContainerLVMUex8/getValidator_ExpressionLanguageService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidator_ExpressionLanguageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'validator.expression_language' shared service.
     *
     * @return \Symfony\Component\ExpressionLanguage\ExpressionLanguage
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['validator.expression_language'] = new \Symfony\Component\ExpressionLanguage\ExpressionLanguage(($container->services['cache.validator_expression_language'] ?? $container->getCache_ValidatorExpressionLanguageService()));
    }
}
