<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXvLjpJL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXvLjpJL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXvLjpJL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXvLjpJL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXvLjpJL\App_KernelDevDebugContainer([
    'container.build_hash' => 'XvLjpJL',
    'container.build_id' => '12807ddf',
    'container.build_time' => 1685110080,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXvLjpJL');
