<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerXOHEcnq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXOHEcnq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXOHEcnq.legacy');
=======
if (\class_exists(\ContainerLVMUex8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLVMUex8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLVMUex8.legacy');
>>>>>>> fd6f3db (PDO INCLUDE MYSQL)

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerXOHEcnq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXOHEcnq\App_KernelDevDebugContainer([
    'container.build_hash' => 'XOHEcnq',
    'container.build_id' => 'a20b57fe',
    'container.build_time' => 1685109081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXOHEcnq');
=======
    \class_alias(\ContainerLVMUex8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLVMUex8\App_KernelDevDebugContainer([
    'container.build_hash' => 'LVMUex8',
    'container.build_id' => '2f2b8f97',
    'container.build_time' => 1685109078,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLVMUex8');
>>>>>>> fd6f3db (PDO INCLUDE MYSQL)
