<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8CobTv6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8CobTv6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8CobTv6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8CobTv6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8CobTv6\App_KernelDevDebugContainer([
    'container.build_hash' => '8CobTv6',
    'container.build_id' => '8e7acfab',
    'container.build_time' => 1685106739,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8CobTv6');
